import { Metadata } from 'next'
import './globals.css'
import { Ubuntu } from 'next/font/google'
import logo from "@/logo.png"
import Banner from '@/components/Banner'
import Navigation from '@/components/Navigation'
import MobileNavigation from '@/components/Navigation/mobile'
import DesktopNavigation from '@/components/Navigation/desktop'
import NextStepNavigation from '@/components/Navigation/next-step'
import Footer from '@/components/Footer'

const ubuntu = Ubuntu({ 
  weight: ['400','500','700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: logo.src
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} w-screen h-screen bg-body-bg pb-16 sm:pb-0`}>
        <Banner/>
        <main className="relative z-10 px-4 sm:max-w-screen-lg sm:mx-auto sm:h-full sm:flex sm:items-center">
          <MobileNavigation/>
          <div className="card bg-white p-3 rounded-lg w-full flex shadow-xl shadow-muted/80">
            <DesktopNavigation/>
            <div className="grow">
              <div className="max-w-lg mx-auto p-4 h-full flex flex-col">
                <div className="grow">
                  {children}
                </div>
                <div className="hidden sm:block">
                  <NextStepNavigation/>
                </div>
              </div>
            </div>
          </div>
        </main>
        <Footer/>
      </body>
    </html>
  )
}
